version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
tls:
  certificate: /etc/docker/registry/registry.crt
  key: /etc/docker/registry/registry.key
